[build-system]
requires = ["uv_build >= 0.10.10, <0.12.0"]
build-backend = "uv_build"

[project]
name = "eqnorm"
version = "0.1.0"
description = "A machine learning potential energy project eqnorm"

authors = [
    { name = "Yuzhuo Chen", email = "chenyuzhuo@zhejianglab.org" },
    { name = "Lyuwen Fu", email = "lyuwenfu@zhejianglab.org" },
    { name = "Shuxiang Yang", email = "yang_shuxiang@zhejianglab.org" },
    { name = "Lipeng Chen", email = "chenlp@zhejianglab.org" },
]

readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

keywords = [
    "machine learning",
    "potential energy",
    "eqnorm",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "torch>=2.6.0",
    "torch_geometric",
    "torchvision==0.21.0",
    "torchaudio==2.6.0",
    "torch_scatter",

    "ase",
    "pyyaml",
    "vesin",
    "e3nn>=0.5.0",
    "wget",
]

[tool.uv]
index-strategy = "unsafe-best-match"
extra-index-url = ["https://download.pytorch.org/whl/cu124"]
find-links = ["https://data.pyg.org/whl/torch-2.6.0+cu124.html"]

[tool.uv.build-backend]
module-name = "eqnorm"
module-root = ""

[tool.uv_build]
include = [
    "eqnorm/**/*.pyi",
    "eqnorm/py.typed",
    "eqnorm/model_settings/**",
]

[project.urls]
Homepage = "https://github.com/yzchen08/eqnorm"
Repository = "https://github.com/yzchen08/eqnorm"